DELETE FROM vtiger_links WHERE linklabel = 'LBL_CALLCENTER_REPORT_CALLS_PURPOSE_TODAY_WIDGET';
DELETE FROM vtiger_links WHERE linklabel = 'LBL_CALLCENTER_REPORT_CALLS_PURPOSE_THIS_WEEK_WIDGET';
DELETE FROM vtiger_links WHERE linklabel = 'LBL_CALLCENTER_REPORT_CALLS_PURPOSE_THIS_MONTH_WIDGET';